name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lucando no Docker v1.${{github.actor}}
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Miguelitando/Emiliano the Docker image
      run: docker build . --file Dockerfile --tag masfelix/node_test
    - name: Jonnytiando imagem
      run: docker push masfelix/node_test
